### ISSUE TITLE
Syntax fix

### ISSUE THREAD

**Issue by timoothee** [PythonClubHub/PythonClub-Learning#12]
When i run the main file, the output looks like this.
![image](https://github.com/PythonClubHub/PythonClub-Learning/assets/115079881/9aa336c0-9636-4853-b20b-77a0ac4f8abc)

I noticed an unwanted forward slash and 'S' char at the beginning of line 3 and 4.
Also on line 2 at the end.

I assume there is a problem here.
https://github.com/PythonClubHub/PythonClub-Learning/blob/Vali/First_Project/main.py#L31

**Comment by BatranuVali** [comment]
S/he is not faulty syntax it is a way of representing both genders in generalized preformatted text. The issue was solved to avoid future confusion.

**Comment by timoothee** [comment]
I understand.. It's the first time i'm seeing this type of representation.
Interesting..
