### ISSUE TITLE
Pronoun mistake

### ISSUE THREAD

**Issue by timoothee** [PythonClubHub/PythonClub-Learning#13]
![image](https://github.com/PythonClubHub/PythonClub-Learning/assets/115079881/84cdc0e0-687c-4728-a44a-fca7bc719855)

What happens if the user it's a girl?
The output will be "He is a student in ..."?

Shouldn't it be 'She' ?

**Comment by BatranuVali** [comment]
S/he is not a mistake it means she/he it's meant to include both genders. For avoiding confusion in future S/he was changed to she/him.
